DefaultTacticsAmbulanceTeam:
  HumanDetector: src.detector.ambulance_detector.AmbulanceDetector
  Search: src.search.ambulance_search.AmbulanceSearch
  ExtendActionTransport: src.extend_action.extend_action_transport.ExtendActionTransport
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorAmbulance: adf_core_python.implement.centralized.default_command_executor_ambulance.DefaultCommandExecutorAmbulance
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsFireBrigade:
  HumanDetector: src.detector.fire_detector.FireDetector
  Search: src.search.fire_search.FireSearch
  ExtendActionRescue: src.extend_action.extend_action_rescue.ExtendActionRescue
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorFire: adf_core_python.implement.centralized.default_command_executor_fire.DefaultCommandExecutorFire
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsPoliceForce:
  RoadDetector: src.detector.police_detector.PoliceDetector
  Search: src.search.police_search.PoliceSearch
  ExtendActionClear: src.extend_action.extend_action_clear.ExtendActionClear
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorPolice: adf_core_python.implement.centralized.default_command_executor_police.DefaultCommandExecutorPolice
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsAmbulanceCenter:
  TargetAllocator: adf_core_python.implement.module.complex.default_ambulance_target_allocator.DefaultAmbulanceTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_ambulance.DefaultCommandPickerAmbulance

DefaultTacticsFireStation:
  TargetAllocator: adf_core_python.implement.module.complex.default_fire_target_allocator.DefaultFireTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_fire.DefaultCommandPickerFire

DefaultTacticsPoliceOffice:
  TargetAllocator: adf_core_python.implement.module.complex.default_police_target_allocator.DefaultPoliceTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_police.DefaultCommandPickerPolice

AmbulanceSearch:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering
  SendMessage: src.communication.send_message.SendMessage

AmbulanceDetector:
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering

FireSearch:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering
  SendMessage: src.communication.send_message.SendMessage

FireDetector:
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering

PoliceSearch:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering
  SendMessage: src.communication.send_message.SendMessage

PoliceDetector:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  Clustering: src.clustering.k_means_pp_clustering.KMeansPPClustering

ExtendActionClear:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

ExtendActionRescue:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

ExtendActionTransport:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultRoadDetector:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultExtendActionClear:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultExtendActionRescue:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultExtendActionMove:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultExtendActionTransport:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultCommandExecutorAmbulance:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  ExtendActionTransport: adf_core_python.implement.action.default_extend_action_transport.DefaultExtendActionTransport
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorFire:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  ExtendActionFireRescue: adf_core_python.implement.action.default_extend_action_rescue.DefaultExtendActionRescue
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorPolice:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  ExtendActionClear: adf_core_python.implement.action.default_extend_action_clear.DefaultExtendActionClear
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorScout:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning

DefaultCommandExecutorScoutPolice:
  PathPlanning: src.path_planning.d_star_lite_path_planning.DStarLitePathPlanning
  ExtendActionClear: adf_core_python.implement.action.default_extend_action_clear.DefaultExtendActionClear

MessageManager:
  PlatoonChannelSubscriber: src.communication.channel_subscriber.PlatoonChannelSubscriber
  CenterChannelSubscriber: adf_core_python.implement.module.communication.default_channel_subscriber.DefaultChannelSubscriber
  PlatoonMessageCoordinator: src.communication.message_coordinator.PlatoonMessageCoordinator
  CenterMessageCoordinator: adf_core_python.implement.module.communication.default_message_coordinator.DefaultMessageCoordinator
